name = "fortumore-cards"
main = "worker.js"
compatibility_date = "2024-09-23"
type = "service"

[env.production]
vars = { ADMIN_TOKEN = "sk-fortumore-default-token" }

[[d1_databases]]
binding = "DB"
database_name = "fortumore-elites"
database_id = "cfa768d7-fc28-4126-a808-75d1d0a2d8fe"

[analytics]
enabled = true
